# Generated by Django 4.2.20 on 2025-09-04 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_customuser_options_remove_company_fleet_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('optimized', 'Optimized'), ('ai_optimized', 'AI Optimized'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_duration', models.IntegerField(default=0)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_efficiency', models.FloatField(default=25.0)),
                ('vehicle_type', models.CharField(default='delivery_van', max_length=50)),
                ('avg_mpg', models.FloatField(default=25.0)),
                ('fuel_capacity', models.FloatField(default=20.0)),
                ('fuel_price', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('original_distance', models.FloatField(blank=True, null=True)),
                ('distance_saved', models.FloatField(blank=True, null=True)),
                ('optimization_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('stop_type', models.CharField(choices=[('search', 'Search Result'), ('manual', 'Manual Pin'), ('fuel_station', 'Fuel Station')], default='search', max_length=20)),
                ('order_index', models.PositiveIntegerField()),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuel_brand', models.CharField(blank=True, max_length=100)),
                ('distance_from_route', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='route_optimizer.route')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['route', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_type', models.CharField(choices=[('standard', 'Standard'), ('gemini_ai', 'Gemini AI')], max_length=20)),
                ('original_order', models.JSONField()),
                ('optimized_order', models.JSONField()),
                ('distance_before', models.FloatField()),
                ('distance_after', models.FloatField()),
                ('distance_saved', models.FloatField()),
                ('fuel_savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gemini_response', models.TextField(blank=True)),
                ('processing_time', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='route_optimizer.route')),
            ],
            options={
                'verbose_name': 'Route Optimization',
                'verbose_name_plural': 'Route Optimizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
