# Generated by Django 4.2.20 on 2025-09-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
