# Generated by Django 4.2.20 on 2025-09-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='averagekmpl',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='averagekmpl',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
